# Generated by Django 5.2.17 on 2026-09-30 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'catégorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='légende')),
                ('image', models.FileField(upload_to='photos/%Y/%m/', verbose_name='photo')),
                ('thumbnail', models.FileField(upload_to='thumbnails/%Y/%m/', verbose_name='miniature')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size', models.PositiveIntegerField(verbose_name='taille enregistrée')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ajoutée le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='gallery.category', verbose_name='catégorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ajoutée par')),
            ],
            options={
                'verbose_name': 'photo',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
